tasks:
  - name: esphome_install
    init: >
      pyenv install 3.9.0 &&
      gp sync-done bundle # 'bundle' is an arbitrary name
    
  - name: esphome_compile
    init: gp sync-await bundle # wait for the above 'init' to finish
    command: esphome dashboard config/
